language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run eslint
  - npm run test
before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  - provider: script
    edge: true
    script: netlify deploy --dir=dist --prod
    on:
      branch: master
  - provider: script
    edge: true
    script: netlify deploy --dir=dist --prod
    on:
      branch: development 