language: node_js
node_js:
  - 12
stages:
  - test
  - build
  - name: deploy-dev
    if: branch = development
  - name: deploy-pro
    if: branch = master

jobs:
  include:
    - script: npm run test

    - stage: build
      script: npm run build

    - stage: deploy-dev
      before_script: npm install netlify-cli -g
      script: netlify deploy --dir=build --message="$TRAVIS_COMMIT_MESSAGE"

    - stage: deploy-pro
      before_script: npm install netlify-cli -g
      script: 
        - npm run build # example
        - netlify deploy --prod --dir=build --message="$TRAVIS_COMMIT_MESSAGE"